# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13S1e2LM8YI9jywuFYq7O3NrXM0qJrNdG

### **Give access to Google Drive**
"""

from google.colab import drive
# Unmount the drive if already mounted
drive.flush_and_unmount()

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount("/content/drive", force_remount=True)
# %cd "/content/drive/My Drive/Colab Notebooks/Ozonation model"

"""### **Preprocessing the dataset**"""

import pandas as pd
import numpy as np
from scipy.signal import find_peaks


def preprocess_pims_data(file_path, volume=573.86):
    # --- 1. Load and Initial Clean ---
    try:
        df = pd.read_csv(file_path, encoding='ISO-8859-1', delimiter=',', skiprows=1, header=None)
    except UnicodeDecodeError:
        df = pd.read_csv(file_path, encoding='cp1252', delimiter=',', skiprows=1, header=None)

    # Set headers and clean up
    df.columns = df.iloc[0]
    df = df[1:].reset_index(drop=True)

    rename_dict = {
        "LDN Transport - Leiduin I Drinkwater [Temperatuur]": "WaterTemperature",
        "LDN effluent snelfiltratie Troebelheid": "RFTurbidity",
        "LDN Ozonisatie - Ozonstraat 1 [Debiet]": "Flow_1",
        "LDN Ozonisatie - Ozonstraat 2 [Debiet]": "Flow_2",
        "LDN Ozonisatie - Ozonstraat 3 [Debiet]": "Flow_3",
        "LDN Ozonisatie - Ozonstraat 4 [Debiet]": "Flow_4",
        "LDN Ozonproductie - Ozongenerator 1 [Debiet Ozongas]": "GasFlow_1",
        "LDN Ozonproductie - Ozongenerator 2 [Debiet Ozongas]": "GasFlow_2",
        "LDN Ozonproductie - Ozongenerator 3 [Debiet Ozongas]": "GasFlow_3",
        "LDN Ozonproductie - Ozongenerator 4 [Debiet Ozongas]": "GasFlow_4",
        "LDN Ozonproductie - Ozongenerator 1 [Actueel Setpoint]": "Setpoint_1",
        "LDN Ozonproductie - Ozongenerator 2 [Actueel Setpoint]": "Setpoint_2",
        "LDN Ozonproductie - Ozongenerator 3 [Actueel Setpoint]": "Setpoint_3",
        "LDN Ozonproductie - Ozongenerator 4 [Actueel Setpoint]": "Setpoint_4",
    }
    df = df.rename(columns=rename_dict)
    df['Date'] = pd.to_datetime(df['Date'])

    # Convert to numeric
    param_cols = [c for c in df.columns if c != 'Date']
    for col in param_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df = df.drop_duplicates(subset='Date').sort_values('Date').reset_index(drop=True)
    df['hour'] = df['Date'].dt.hour
    df['month'] = df['Date'].dt.month

    # --- 2. Threshold Cleaning (Temperature & Zeros) ---
    # Monthly/Hourly profile for imputation
    temp_profile = df.groupby(['month', 'hour'])['WaterTemperature'].transform('mean')

    # Apply Temperature Thresholds
    df.loc[(df['WaterTemperature'] > 25) | (df['WaterTemperature'] < 1.2), 'WaterTemperature'] = temp_profile

    # Remove Zeros/Low values for Flow, GasFlow, and Setpoint by replacing with group median
    sensor_cols = [c for c in df.columns if any(x in c for x in ['Flow', 'GasFlow', 'Setpoint'])]
    for col in sensor_cols:
        # Define zero/near-zero threshold (e.g., < 0.1)
        mask = df[col] <= 0.1
        df.loc[mask, col] = df.groupby(['month', 'hour'])[col].transform('median')

    # --- 3. Chamber Logic, Dosage, & Residence Time ---
    chamber_list = []
    # Assuming 5-minute data (12 rows = 1 hour lag)
    LAG_STEPS = 1

    for i in range(1, 5):
        # Calculate Dosage and Residence Time per chamber
        flow_col = df[f'Flow_{i}']
        dosage = (df[f'GasFlow_{i}'] * df[f'Setpoint_{i}']) / flow_col
        res_time = (volume * 60) / flow_col

        temp_df = pd.DataFrame({
            'Date': df['Date'],
            'month': df['month'],
            'WaterTemperature': df['WaterTemperature'],
            'RFTurbidity': df['RFTurbidity'],
            'FlowRate': flow_col,
            'Ozonedosage': dosage,
            'ResidenceTime': res_time,
            'Chamber': i
        })

        # --- 4. One-Hour Time Lag for ALL parameters ---
        cols_to_lag = ['WaterTemperature', 'RFTurbidity', 'Flow', 'Dosage']
        for col in cols_to_lag:
            temp_df[f'{col}_1'] = temp_df[col].shift(LAG_STEPS)

        chamber_list.append(temp_df)

    # --- 5. Combine and Finalize ---
    final_pims = pd.concat(chamber_list, axis=0).reset_index(drop=True)
    final_pims = final_pims.dropna() # Remove rows where lags are empty

    return final_pims

def predict_next_step(current_raw, chamber_id, volume=573.86):
    """
    Cleverly uses the cached 'last state' as the 'lag' to avoid double processing.
    """
    global last_state_cache

    # 1. Standardize and Rename the NEW incoming data
    rename_dict = {
        "LDN Transport - Leiduin I Drinkwater [Temperatuur]": "WaterTemperature",
        "LDN effluent snelfiltratie Troebelheid": "RFTurbidity",
        f"LDN Ozonisatie - Ozonstraat {chamber_id} [Debiet]": "Flow",
        f"LDN Ozonproductie - Ozongenerator {chamber_id} [Debiet Ozongas]": "GasFlow",
        f"LDN Ozonproductie - Ozongenerator {chamber_id} [Actueel Setpoint]": "Setpoint",
    }

    # Clean/Rename current row
    data = current_raw.rename(columns=rename_dict) if isinstance(current_raw, pd.DataFrame) else current_raw.rename(index=rename_dict)

    # 2. Process NEW step only
    flow = float(data['Flow'])
    gas = float(data['GasFlow'])
    setpoint = float(data['Setpoint'])

    curr_processed = {
        'month': pd.to_datetime(data['Date']).month,
        'WaterTemperature': float(data['WaterTemperature']),
        'RFTurbidity': float(data['RFTurbidity']),
        'FlowRate': flow,
        'Ozonedosage': (gas * setpoint) / flow if flow > 0 else 0,
        'Residencetime': (volume * 60) / flow if flow > 0 else 0
    }

    # 3. Check if we have the "Lag" (Previous Step) in cache
    if chamber_id not in last_state_cache:
        # First run: we can't predict yet. Save current and return None.
        last_state_cache[chamber_id] = curr_processed
        print(f"Chamber {chamber_id}: Initialized. Waiting for next hour to predict.")
        return None

    prev_processed = last_state_cache[chamber_id]

    # 4. Construct the Prediction Row (Combining New + Cached Lag)
    prediction_row = {
        # Current Features
        **curr_processed,
        'Chamber': chamber_id,

        # Lagged Features (Pulled directly from Cache)

        'WaterTemperature_1': prev_processed['WaterTemperature'],
        'RFTurbidity_1': prev_processed['RFTurbidity'],
        'FlowRate_1': prev_processed['Flow'],
        'Ozonedosage_1': prev_processed['Dosage']
    }

    # 5. UPDATE CACHE: Current becomes the "Previous" for the next hour
    last_state_cache[chamber_id] = curr_processed

    return pd.DataFrame([prediction_row])